AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Index:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: s3://aws-lambda-dynamodb/65d2d40249424602a42fe8053b3df06b
      Environment:
        Variables:
          AWS_DYNAMODB_ENDPOINT: http://docker.for.mac.host.internal:8000
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
  One:
    Type: AWS::Serverless::Function
    Properties:
      Handler: one-record.handler
      Runtime: nodejs10.x
      CodeUri: s3://aws-lambda-dynamodb/65d2d40249424602a42fe8053b3df06b
      Environment:
        Variables:
          AWS_DYNAMODB_ENDPOINT: http://docker.for.mac.host.internal:8000
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /record/{key}
            Method: GET
  PersonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: personsKey
        AttributeType: S
      - AttributeName: firstName
        AttributeType: S
      - AttributeName: lastName
        AttributeType: S
      KeySchema:
      - AttributeName: personsKey
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
