AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Index:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: s3://aws-lambda-dynamodb/779debd8e4e910f895b85c6725611510
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
