AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Index:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: s3://aws-lambda-dynamodb/bcf11efa1c77ca99cf90f734f583f704
      Environment:
        Variables:
          AWS_DYNAMODB_ENDPOINT: http://docker.for.mac.host.internal:8000
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
  Post:
    Type: AWS::Serverless::Function
    Properties:
      Handler: post.handler
      Runtime: nodejs10.x
      CodeUri: s3://aws-lambda-dynamodb/bcf11efa1c77ca99cf90f734f583f704
      Environment:
        Variables:
          AWS_DYNAMODB_ENDPOINT: http://docker.for.mac.host.internal:8000
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /post
            Method: GET
  One:
    Type: AWS::Serverless::Function
    Properties:
      Handler: one-record.handler
      Runtime: nodejs10.x
      CodeUri: s3://aws-lambda-dynamodb/bcf11efa1c77ca99cf90f734f583f704
      Environment:
        Variables:
          AWS_DYNAMODB_ENDPOINT: http://docker.for.mac.host.internal:8000
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /record/{key}
            Method: GET
  PersonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Persons
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      KeySchema:
      - AttributeName: personKey
        KeyType: HASH
      AttributeDefinitions:
      - AttributeName: personKey
        AttributeType: S
