AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Index:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: s3://aws-lambda-dynamodb/e4ae42250a6d26a8f52b626dc7046b06
      Environment:
        Variables:
          AWS_DYNAMODB_ENDPOINT: http://docker.for.mac.host.internal:8000
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
